/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'doc',
          id: 'reference/access-permissions',
          label: 'Access Permissions',
        },
        {
          type: 'category',
          label: 'Command-Line Interface (CLI)',
          items: [
            {
              type: 'autogenerated',
              dirName: 'reference/cli',
            },
          ],
        },
        {
          type: 'link',
          label: 'Resoto Core API',
          href: '/docs/reference/resotocore-api',
        },
        {
          type: 'category',
          label: 'Resources',
          items: [
            {
              type: 'autogenerated',
              dirName: 'reference/resources',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contributing',
        },
      ],
    },
  ],
};

module.exports = sidebars;
