name: 🐞 Bug Report
description: Report a problem
labels: ['🐞 bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the bug or issue.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, please provide screenshots depicting the problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional information or screenshots that may be relevant or helpful.
  - type: markdown
    attributes:
      value: |
        By submitting this bug report, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).
