name: Update Labels

on:
  push:
    branches:
      - main
    paths:
      - '.github/**/labels.yml'
  workflow_dispatch:

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Update labels
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
