import requests
from textwrap import dedent

core = "http://localhost:8900"
info = requests.get(f"{core}/cli/info").json()
commands = {cmd["name"]: cmd for cmd in info["commands"]}


def preamble():
  print(dedent("""
  <!--

  NOTE: THIS DOCUMENT IS GENERATED. DO NOT EDIT THIS FILE MANUALLY.

  Instead, use `export_cli_reference.py` to update the generator.

  -->

  # Command-Line Interface (CLI)

  ```mdx-code-block
  import { useCurrentSidebarCategory } from '@docusaurus/theme-common';
  import DocCardList from '@theme/DocCardList';
  ```

  The [`resh`](/concepts/components/shell.md) CLI supports various commands that help you accessing the graph database.

  :::tip

  You can pipe commands using `|` and chain multiple commands using `;`.

  :::
  """))


def commands_overview():
  print("\n\n## Commands\n\n")
  print("| Command  |  Description |")
  print("|----------|--------------|")
  for name, cmd in sorted(commands.items()):
    print(f'|[`{name}`](#{name})|{cmd["info"]}|')


def command_help():
  for name, cmd in sorted(commands.items()):
    print(f"\n\n### {name}\n\n")
    print(f'**{cmd["info"]}**')
    print("\n\n")
    print(cmd["help"].replace("<", "&lt;").replace(">", "&gt;"))


def command_aliases():
  print("\n\n## Command Aliases\n\n")
  print("| Alias  |  Command | Description |")
  print("|--------|----------|-------------|")
  for alias, cmd in sorted(info["aliases"].items()):
    print(f'|`{alias}`|`{cmd}`|{commands[cmd]["info"]}|')


def replacements():
  print("\n\n## Placeholder Strings\n\n")
  print("| Placeholder  |  Example |")
  print("|--------------|----------|")
  for k, v in sorted(info["replacements"].items()):
    print(f'|`@{k}@`|`{v}`|')


preamble()
commands_overview()
command_help()
command_aliases()
replacements()
